services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.3/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mariadb
    mariadb:
        image: bitnami/mariadb:latest
        volumes:
            - './sail-db:/bitnami/mariadb/data'
        restart: always
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            ALLOW_EMPTY_PASSWORD: 1
            MARIADB_EXTRA_FLAGS: '--max-connect-errors=1000 --max_connections=155'
            MARIADB_CHARACTER_SET: utf8
            MARIADB_COLLATE: utf8_general_ci
            MARIADB_ROOT_USER: root
            MARIADB_ROOT_PASSWORD: 'password'
            MARIADB_PORT_NUMBER: 3306
            MARIADB_DATABASE: 'laravel'
            MARIADB_USER: sail
            MARIADB_PASSWORD: 'password'
            MARIADB_ENABLE_SLOW_QUERY: 0
            MARIADB_LONG_QUERY_TIME: 10.0
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
